version: "3.9"
services:
  backend:
    container_name: library_be
    build:
      context: ./backend/
    ports:
      - "8085:8085"
    depends_on: 
      - db
  db:
    image: postgres:latest
    container_name: library_db
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
  frontend:
    container_name: library_fe
    build:
      context: ./frontend/
    ports:
      - "3000:3000"
