version: "3.9"
services:
  backend:
    container_name: library_be
    build:
      context: ./backend/
    ports:
      - "8085:8085"
    environment:
      - DB=test # database
      - DB_HOST=192.168.1.5 # db host: please mention ip address
      - DB_PASS=test # db user password
      - DB_PORT=5432 # db port
      - DB_USER=test # db use
  frontend:
    container_name: library_fe
    build:
      context: ./frontend/
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BE_IP_ADDRESS=192.168.1.5
    depends_on:
      - backend
