apiVersion: v1
kind: Service
metadata:
  name: library-backend
spec:
  selector:
    library: be
  type: NodePort
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30085
