server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:192.168.1.5}:${DB_PORT:5432}/${DB:test}
    username: ${DB_USER:test}
    password: ${DB_PASS:test}
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
